### ISSUE TITLE
Is there any way to use middleware, or ctx context

### ISSUE THREAD

**Issue by skyisboss** [Squirrel-Network/gobotapi#6]
example, save the user's session

**Comment by Laky-64** [comment]
Yep, recently was added the client context, you can see the example:

https://github.com/Squirrel-Network/gobotapi/blob/master/examples/download_files/main.go#L27

**Comment by skyisboss** [comment]
> Yep, recently was added the client context, you can see the example:
> 
> https://github.com/Squirrel-Network/gobotapi/blob/master/examples/download_files/main.go#L27

hi ,is there can use a global middleware like the gin framework? When the robot has an update message, always execute this global middleware first,Therefore, similar session storage, internationalization settings, etc. can be implemented in the middleware

**Comment by Laky-64** [comment]
Hello, in practice would you like to implement a wrapper of a listener?

**Comment by Laky-64** [comment]
You can add it, like how filters works

**Comment by skyisboss** [comment]
sorry for the late reply，I just saw the latest examples and it's great😀 grateful

**Comment by Laky-64** [comment]
Ok, thanks ❤️, I will close this issue
